import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Makes `account_invitation.token` a real unique credential (DDD Exemplar 1).
 *
 * The initial migration baked a FROZEN default —
 * `DEFAULT '3c8a0348-5d51-44eb-af03-8d77f28bc253'` — because `@Column({ default:
 * randomUUID() })` was evaluated once at class-load, so every tokenless row shares one
 * UUID. Adding `UNIQUE(token)` naively would throw `duplicate key`. The safe sequence:
 * backfill the collided rows, drop the default, THEN add a soft-delete-aware partial
 * unique index — deployed atomically with the code cutover that generates tokens in the
 * domain (`Token.create`).
 */
export class AccountInvitationTokenUnique1785874104000 implements MigrationInterface {
    name = 'AccountInvitationTokenUnique1785874104000';

    public async up(queryRunner: QueryRunner): Promise<void> {
        // 1. Backfill any rows still carrying the frozen class-load default so the unique
        //    index can be created. No-op on a fresh DB; the remediation for a deployed one.
        await queryRunner.query(`
            UPDATE "account_invitation"
            SET "token" = uuid_generate_v4()::varchar
            WHERE "token" = '3c8a0348-5d51-44eb-af03-8d77f28bc253'
        `);

        // 2. Drop the frozen column default — tokens are now generated by the domain
        //    (Token.create). Keep NOT NULL; the app always supplies a token on insert.
        await queryRunner.query(`
            ALTER TABLE "account_invitation" ALTER COLUMN "token" DROP DEFAULT
        `);

        // 3. Soft-delete-aware partial unique index (a plain unique would count
        //    soft-deleted rows and block re-issuing a token).
        await queryRunner.query(`
            CREATE UNIQUE INDEX "UQ_account_invitation_token"
            ON "account_invitation" ("token")
            WHERE "deleted_at" IS NULL
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP INDEX "UQ_account_invitation_token"
        `);
        // Intentionally does NOT restore the frozen (buggy) default.
    }
}
