version: '3.8'
services:
    postgres:
        image: postgres:17
        container_name: objects-subscription-service-database
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '5432:5432'
        networks:
            - postgres-network

    broker1:
        image: confluentinc/cp-kafka:7.8.0
        hostname: broker1
        ports:
            - '9092:9092'
        environment:
            KAFKA_NODE_ID: 1
            CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,LISTENER_ONE:PLAINTEXT,LISTENER_TWO:PLAINTEXT'
            KAFKA_ADVERTISED_LISTENERS: 'LISTENER_ONE://broker1:29092,LISTENER_TWO://127.0.0.1:9092'
            KAFKA_PROCESS_ROLES: 'broker,controller'
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:29093'
            KAFKA_LISTENERS: 'CONTROLLER://broker1:29093,LISTENER_ONE://broker1:29092,LISTENER_TWO://0.0.0.0:9092'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_ONE'
            KAFKA_LOG_RETENTION_MS: '600000'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        healthcheck:
            test: >
                kafka-topics --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic create.organization || exit 1 &&
                kafka-topics --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic create.organization.two || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        environment:
            KAFKA_CLUSTERS_0_NAME: 'The Cluster'
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker1:29092'
        ports:
            - '8080:8080'
        depends_on:
            - broker1

networks:
    postgres-network:
        driver: bridge
