import {
    BaseEntity,
    Column,
    CreateDateColumn,
    DeleteDateColumn,
    Entity,
    Index,
    JoinColumn,
    ManyToOne,
    PrimaryGeneratedColumn,
    UpdateDateColumn,
} from 'typeorm';
import type { Relation } from 'typeorm';
import { AccountDao } from './account.dao.js';
import { AccountInvitationEntity } from '../domain/account-invitation.entity.js';

@Entity({ name: 'account_invitation' })
// Soft-delete-aware unique token (matches the partial index in the migration). The
// token is generated by the domain (Token.create) — no DB-level default (see below).
@Index('UQ_account_invitation_token', ['token'], { unique: true, where: '"deleted_at" IS NULL' })
export class AccountInvitationDao extends BaseEntity {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({ type: 'uuid' })
    accountId: string;

    @JoinColumn({ name: 'account_id', referencedColumnName: 'id' })
    @ManyToOne(() => AccountDao, account => account.invitations, {
        onDelete: 'CASCADE',
    })
    account?: Relation<AccountDao>;

    @Column({ type: 'varchar' })
    token: string;

    @Column({ type: 'boolean', default: true })
    isValid: boolean;

    @CreateDateColumn()
    createdAt: Date;

    @Column({ type: 'varchar', nullable: true })
    createdBy?: string;

    @UpdateDateColumn()
    updatedAt: Date;

    @Column({ type: 'varchar', nullable: true })
    updatedBy?: string;

    @Column({ type: 'varchar', nullable: true })
    deletedBy?: string | null;

    @DeleteDateColumn()
    deletedAt?: Date | null;

    get toEntity(): AccountInvitationEntity {
        return AccountInvitationEntity.reconstitute({
            id: this.id,
            accountId: this.accountId,
            account: this.account?.toEntity,
            token: this.token,
            isValid: this.isValid,
            createdAt: this.createdAt,
            createdBy: this.createdBy,
            updatedAt: this.updatedAt,
            updatedBy: this.updatedBy,
            deletedBy: this.deletedBy,
            deletedAt: this.deletedAt,
        });
    }
}
