name: Create Release

concurrency:
    group: ${{ github.ref_name }}
    cancel-in-progress: true

on:
    push:
        branches: [development, production]

jobs:
    create-tag:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.CI_TOKEN }}
                  ref: ${{ github.event.workflow_run.head_branch }}

            - name: Setup Node
              uses: ./.github/actions/setup-node
              with:
                  node-version: 22
                  node-auth-token: ${{ secrets.CI_TOKEN }}

            - name: Create Release
              run: |
                  npm i semantic-release -g
                  GITHUB_REF=${{ github.ref_name }}
                  npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
